# Generated by Django 4.1.7 on 2023-03-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
