# Generated by Django 4.1.7 on 2023-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dish_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_id',
            field=models.IntegerField(unique=True),
        ),
    ]
